services:
  postgres:
    image: postgres:16
    container_name: bank_postgres
    environment:
      POSTGRES_USER: de
      POSTGRES_PASSWORD: de
      POSTGRES_DB: abnk
      TZ: Asia/Kathmandu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: